/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ["./src/**/*.tsx"],
  theme: {
    extend: {
      colors: {
        "color-primary": {
          DEFAULT: "rgb(var(--primary-6))",
          hover: "rgb(var(--primary-5))",
          click: "rgb(var(--primary-7))",
          1: "rgb(var(--primary-1))",
          2: "rgb(var(--primary-2))",
          3: "rgb(var(--primary-3))",
          4: "rgb(var(--primary-4))",
          5: "rgb(var(--primary-5))",
          6: "rgb(var(--primary-6))",
          7: "rgb(var(--primary-7))",
        },
        "color-success": {
          DEFAULT: "var(--success-6)",
          hover: "var(--success-5)",
          click: "var(--success-7)",
          1: "var(--success-1)",
          2: "var(--success-2)",
          3: "var(--success-3)",
          4: "var(--success-4)",
          5: "var(--success-5)",
          6: "var(--success-6)",
          7: "var(--success-7)",
        },
        "color-warning": {
          DEFAULT: "var(--success-6)",
          hover: "var(--success-5)",
          click: "var(--success-7)",
          1: "var(--warning-1)",
          2: "var(--warning-2)",
          3: "var(--warning-3)",
          4: "var(--warning-4)",
          5: "var(--warning-5)",
          6: "var(--warning-6)",
          7: "var(--warning-7)",
        },
        "color-danger": {
          DEFAULT: "var(--danger-6)",
          hover: "var(--danger-5)",
          click: "var(--danger-7)",
          1: "var(--danger-1)",
          2: "var(--danger-2)",
          3: "var(--danger-3)",
          4: "var(--danger-4)",
          5: "var(--danger-5)",
          6: "var(--danger-6)",
          7: "var(--danger-7)",
        },
        "color-link": {
          DEFAULT: "var(--link-6)",
          hover: "var(--link-5)",
          click: "var(--link-7)",
          1: "var(--link-1)",
          2: "var(--link-2)",
          3: "var(--link-3)",
          4: "var(--link-4)",
          5: "var(--link-5)",
          6: "var(--link-6)",
          7: "var(--link-7)",
        },
        "color-border": {
          DEFAULT: "var(--color-border-1)",
          1: "var(--color-border-1)",
          2: "var(--color-border-2)",
          3: "var(--color-border-3)",
          4: "var(--color-border-4)",
        },
        "color-fill": {
          DEFAULT: "var(--color-fill-1)",
          1: "var(--color-fill-1)",
          2: "var(--color-fill-2)",
          3: "var(--color-fill-3)",
          4: "var(--color-fill-4)",
        },
        "color-text": {
          DEFAULT: "var(--color-text-1)",
          1: "var(--color-text-1)",
          2: "var(--color-text-2)",
          3: "var(--color-text-3)",
          4: "var(--color-text-4)",
        },
        "color-bg": {
          DEFAULT: "var(--color-bg-1)",
          1: "var(--color-bg-1)",
          2: "var(--color-bg-2)",
          3: "var(--color-bg-3)",
          4: "var(--color-bg-4)",
          white: "var(--color-bg-white)",
        },
      },
    },
  },
  plugins: [],
};
